spring:
  application:
    name: Author book rest
  datasource:
    url: jdbc:mysql://localhost:3306/author_book?createDatabaseIfNotExist=true
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:rootroot}
  liquibase:
    change-log: classpath:/db/changelog.xml

jwt:
  secret: YXNkZmYkIyNzZFNEU0RBQVNERksjQEBkc2ZqZGZrZHNqQEAjZHNmZ2ZnZmdeXiYmWipeJSQkI2RzZHMkIyVzZDQ1MDk5KUkjJCg5V0ZTSUo=
  expiration: 600000

run:
  security: false
